+ resolved IndexError: invalid index of a 0-dim tensor
IndexError: invalid index of a 0-dim tensor. Use `tensor.item()` in Python, Solved by using .item() instead of  0-dim tensor