+ resolved AttributeError: 'SummaryWriter' object has no attribute 'add_summary'
AttributeError: 'SummaryWriter' object has no attribute 'add_summary'. Solved using add_scaler instead of add_summary