+ resolved AttributeError: 'SummaryWriter' object has no attribute 'add_summary' (#7)
AttributeError: 'SummaryWriter' object has no attribute 'add_summary'. Solved using add_scaler instead of add_summary